# -*- coding: utf-8 -*-
"""app.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ZoVm35bbCaV7779s2Dsql8v4xLdlMZfC
"""

import streamlit as st
import torch
from transformers import PreTrainedTokenizerFast, BartForConditionalGeneration
import requests
from bs4 import BeautifulSoup

# 1. 페이지 기본 설정 (탭 이름, 아이콘 등)
st.set_page_config(page_title="외교부 소식 요약 봇", page_icon="🤖")

# 2. 모델과 토크나이저 불러오기 (캐싱을 사용하여 속도 향상)
# 주의: 'final_model' 폴더가 app.py와 같은 위치에 있어야 합니다.
@st.cache_resource
def load_model():
    try:
        model_path = "./final_model"  # 폴더 이름
        tokenizer = PreTrainedTokenizerFast.from_pretrained(model_path)
        model = BartForConditionalGeneration.from_pretrained(model_path)
        return tokenizer, model
    except Exception as e:
        st.error(f"모델을 불러오는 중 오류가 발생했습니다. 폴더 위치를 확인해주세요! 에러 내용: {e}")
        return None, None

tokenizer, model = load_model()

# 3. 텍스트 요약 함수
def summarize_text(text):
    if not text:
        return "요약할 내용이 없습니다."

    # 모델 입력 데이터로 변환
    input_ids = tokenizer.encode(text, return_tensors="pt")

    # 모델이 요약문 생성
    summary_text_ids = model.generate(
        input_ids=input_ids,
        bos_token_id=model.config.bos_token_id,
        eos_token_id=model.config.eos_token_id,
        length_penalty=2.0,
        max_length=128,
        min_length=32,
        num_beams=4,
    )

    # 숫자로 된 결과를 다시 글자로 변환
    return tokenizer.decode(summary_text_ids[0], skip_special_tokens=True)

# 4. 웹사이트 본문 긁어오기 (크롤링) 함수
def scrape_text(url):
    try:
        headers = {
            "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.124 Safari/537.36"
        }
        response = requests.get(url, headers=headers)
        soup = BeautifulSoup(response.text, 'html.parser')

        # 네이버 블로그인 경우 (iframe 처리)
        if "blog.naver.com" in url:
            iframe = soup.select_one("iframe#mainFrame")
            if iframe:
                blog_url = "https://blog.naver.com" + iframe["src"]
                response = requests.get(blog_url, headers=headers)
                soup = BeautifulSoup(response.text, 'html.parser')

        # 본문 텍스트 추출 (p 태그나 div 태그 위주)
        # 네이버 블로그 본문 클래스 등을 타겟팅
        content = ""
        main_container = soup.select_one(".se-main-container") or soup.select_one(".post-view")

        if main_container:
            content = main_container.get_text("\n")
        else:
            # 일반 뉴스 사이트 등
            paragraphs = soup.find_all('p')
            content = " ".join([p.get_text() for p in paragraphs])

        return content.strip()[:2000] # 너무 길면 모델이 힘들어하므로 앞부분 2000자만 사용

    except Exception as e:
        return f"에러 발생: {e}"

# 5. 외교부 블로그 최신 글 가져오기 (RSS 대용 간단 크롤링)
def get_mofa_news():
    url = "https://blog.naver.com/PostList.naver?blogId=mofakr&categoryNo=0" # 외교부 블로그 전체글
    headers = {
            "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.124 Safari/537.36"
    }
    response = requests.get(url, headers=headers)
    soup = BeautifulSoup(response.text, 'html.parser')

    # 최신 글 제목과 링크 3개만 가져오기 (예시 구조)
    news_list = []
    titles = soup.select("span.ell") # 네이버 모바일/리스트 뷰 클래스명 추정

    # 간단하게 구현하기 위해 하드코딩된 예시 데이터를 반환하거나
    # 실제로는 네이버 블로그 구조에 맞춰 정확한 파싱이 필요합니다.
    # 여기서는 'URL 요약' 기능이 메인이므로, 외교부 공식 블로그 링크를 안내하는 방식으로 구성합니다.

    return [
        {"title": "외교부 공식 블로그 바로가기 (클릭해서 URL을 복사해보세요)", "link": "https://blog.naver.com/mofakr"},
        {"title": "[예시] 최근 외교부 보도자료", "link": "https://www.mofa.go.kr/www/brd/m_4080/list.do"}
    ]


# --- 메인 화면 구성 (UI) ---

st.title("📰 외교부 소식 자동 요약 봇")
st.write("인공지능이 복잡한 뉴스를 3줄로 요약해 드립니다.")

if model is None:
    st.error("⚠️ 'final_model' 폴더가 없습니다. 같은 폴더에 모델을 넣어주세요!")
else:
    st.success("AI 모델 준비 완료! (Ready)")

# 탭 만들기
tab1, tab2 = st.tabs(["🔗 URL 요약하기", "📢 외교부 소식통"])

# [Tab 1] URL 입력해서 요약하기
with tab1:
    st.header("뉴스/블로그 주소 입력")
    input_url = st.text_input("요약하고 싶은 네이버 블로그나 뉴스 기사 URL을 입력하세요:")

    if st.button("요약 시작"):
        if input_url:
            with st.spinner('뉴스 내용을 읽어오고 요약하는 중입니다...'):
                # 1. 크롤링
                raw_text = scrape_text(input_url)

                if "에러 발생" in raw_text:
                    st.error(raw_text)
                elif len(raw_text) < 50:
                    st.warning("내용을 가져오지 못했습니다. 본문이 너무 짧거나 접근이 막혀있을 수 있습니다.")
                else:
                    # 2. 요약
                    summary = summarize_text(raw_text)

                    st.subheader("📝 요약 결과")
                    st.info(summary)

                    with st.expander("원본 내용 보기"):
                        st.write(raw_text)
        else:
            st.warning("URL을 입력해주세요!")

# [Tab 2] 외교부 소식 가져오기
with tab2:
    st.header("외교부 최신 소식")
    st.write("아래 버튼을 누르면 외교부 관련 링크를 가져옵니다.")

    if st.button("최신 소식 가져오기"):
        news_items = get_mofa_news()

        for item in news_items:
            st.markdown(f"**📌 {item['title']}**")
            st.write(f"링크: {item['link']}")
            st.write("---")

        st.info("💡 위 링크 중 하나를 복사해서 https://blog.naver.com/gjfls01/221792823369?viewType=pc 탭에 넣어보세요!")